// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyKhachSan.Data;

#nullable disable

namespace QuanLyKhachSan.Migrations
{
    [DbContext(typeof(HotelDbContext))]
    [Migration("20260328091200_Create-Database")]
    partial class CreateDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuanLyKhachSan.Models.Account", b =>
                {
                    b.Property<string>("Username")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("taiKhoan");

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("maNV");

                    b.Property<int>("IsDeleted")
                        .HasColumnType("int")
                        .HasColumnName("xuLy");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("matKhau");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("maPQ");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("tinhTrang");

                    b.HasKey("Username");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("RoleId");

                    b.ToTable("TAIKHOAN");
                });

            modelBuilder.Entity("QuanLyKhachSan.Models.Amenity", b =>
                {
                    b.Property<string>("AmenityId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("maTI");

                    b.Property<int>("IsDeleted")
                        .HasColumnType("int")
                        .HasColumnName("xuLy");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("tenTI");

                    b.HasKey("AmenityId");

                    b.ToTable("TIENICH");
                });

            modelBuilder.Entity("QuanLyKhachSan.Models.Customer", b =>
                {
                    b.Property<string>("CustomerId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("maKH");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("queQuan");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngaySinh");

                    b.Property<int>("Gender")
                        .HasColumnType("int")
                        .HasColumnName("gioiTinh");

                    b.Property<string>("IdNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("CMND");

                    b.Property<int>("IsDeleted")
                        .HasColumnType("int")
                        .HasColumnName("xuLy");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("tenKH");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("quocTich");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("sDT");

                    b.HasKey("CustomerId");

                    b.ToTable("KHACHHANG");
                });

            modelBuilder.Entity("QuanLyKhachSan.Models.Employee", b =>
                {
                    b.Property<string>("EmployeeId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("maNV");

                    b.Property<int>("DailySalary")
                        .HasColumnType("int")
                        .HasColumnName("luong1Ngay");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngaySinh");

                    b.Property<int>("DaysOff")
                        .HasColumnType("int")
                        .HasColumnName("soNgayPhep");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<int>("Gender")
                        .HasColumnType("int")
                        .HasColumnName("gioiTinh");

                    b.Property<int>("IsDeleted")
                        .HasColumnType("int")
                        .HasColumnName("xuLy");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("tenNV");

                    b.Property<int>("Position")
                        .HasColumnType("int")
                        .HasColumnName("chucVu");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngayVaoLam");

                    b.HasKey("EmployeeId");

                    b.ToTable("NHANVIEN");
                });

            modelBuilder.Entity("QuanLyKhachSan.Models.Function", b =>
                {
                    b.Property<string>("FunctionId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("maChucNang");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("tenChucNang");

                    b.HasKey("FunctionId");

                    b.ToTable("CHUCNANG");
                });

            modelBuilder.Entity("QuanLyKhachSan.Models.Invoice", b =>
                {
                    b.Property<string>("InvoiceId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("maHD");

                    b.Property<int>("Discount")
                        .HasColumnType("int")
                        .HasColumnName("giamGia");

                    b.Property<int>("IsDeleted")
                        .HasColumnType("int")
                        .HasColumnName("xuLy");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngayThanhToan");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("int")
                        .HasColumnName("phuongThucThanhToan");

                    b.Property<string>("RentalDetailId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("maCTT");

                    b.Property<int>("Surcharge")
                        .HasColumnType("int")
                        .HasColumnName("phuThu");

                    b.HasKey("InvoiceId");

                    b.HasIndex("RentalDetailId");

                    b.ToTable("HOADON");
                });

            modelBuilder.Entity("QuanLyKhachSan.Models.RentalDetail", b =>
                {
                    b.Property<string>("RentalDetailId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("maCTT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngayLapPhieu");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("maKH");

                    b.Property<int>("DepositAmount")
                        .HasColumnType("int")
                        .HasColumnName("tienDatCoc");

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("maNV");

                    b.Property<int>("IsDeleted")
                        .HasColumnType("int")
                        .HasColumnName("xuLy");

                    b.Property<int>("ProcessingStatus")
                        .HasColumnType("int")
                        .HasColumnName("tinhTrangXuLy");

                    b.HasKey("RentalDetailId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("CHITIETTHUE");
                });

            modelBuilder.Entity("QuanLyKhachSan.Models.Role", b =>
                {
                    b.Property<string>("RoleId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("maPQ");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("tenPQ");

                    b.HasKey("RoleId");

                    b.ToTable("PHANQUYEN");
                });

            modelBuilder.Entity("QuanLyKhachSan.Models.RoleFunction", b =>
                {
                    b.Property<string>("RoleId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("maPQ");

                    b.Property<string>("FunctionId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("maChucNang");

                    b.HasKey("RoleId", "FunctionId");

                    b.HasIndex("FunctionId");

                    b.ToTable("CHITIETCHUCNANG");
                });

            modelBuilder.Entity("QuanLyKhachSan.Models.Room", b =>
                {
                    b.Property<string>("RoomId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("maP");

                    b.Property<int>("CurrentCondition")
                        .HasColumnType("int")
                        .HasColumnName("hienTrang");

                    b.Property<int>("IsDeleted")
                        .HasColumnType("int")
                        .HasColumnName("xuLy");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("tenP");

                    b.Property<int>("Price")
                        .HasColumnType("int")
                        .HasColumnName("giaP");

                    b.Property<int>("RoomType")
                        .HasColumnType("int")
                        .HasColumnName("loaiP");

                    b.Property<int>("RoomTypeDetails")
                        .HasColumnType("int")
                        .HasColumnName("chiTietLoaiP");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("tinhTrang");

                    b.HasKey("RoomId");

                    b.ToTable("PHONG");
                });

            modelBuilder.Entity("QuanLyKhachSan.Models.RoomAmenity", b =>
                {
                    b.Property<string>("RoomId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("maP");

                    b.Property<string>("AmenityId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("maTI");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("soLuong");

                    b.HasKey("RoomId", "AmenityId");

                    b.HasIndex("AmenityId");

                    b.ToTable("CHITIETTIENICH");
                });

            modelBuilder.Entity("QuanLyKhachSan.Models.RoomRentalDetail", b =>
                {
                    b.Property<string>("RentalDetailId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("maCTT");

                    b.Property<string>("RoomId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("maP");

                    b.Property<DateTime>("RentalDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngayThue");

                    b.Property<DateTime>("CheckoutDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngayCheckOut");

                    b.Property<int>("RentalPrice")
                        .HasColumnType("int")
                        .HasColumnName("giaThue");

                    b.Property<int>("RentalType")
                        .HasColumnType("int")
                        .HasColumnName("loaiHinhThue");

                    b.Property<DateTime>("ReturnDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngayTra");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("tinhTrang");

                    b.HasKey("RentalDetailId", "RoomId", "RentalDate");

                    b.HasIndex("RoomId");

                    b.ToTable("CHITIETTHUEPHONG");
                });

            modelBuilder.Entity("QuanLyKhachSan.Models.Service", b =>
                {
                    b.Property<string>("ServiceId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("maDV");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("hinhAnh");

                    b.Property<int>("IsDeleted")
                        .HasColumnType("int")
                        .HasColumnName("xuLy");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("tenDV");

                    b.Property<int>("Price")
                        .HasColumnType("int")
                        .HasColumnName("giaDV");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("loaiDV");

                    b.HasKey("ServiceId");

                    b.ToTable("DICHVU");
                });

            modelBuilder.Entity("QuanLyKhachSan.Models.ServiceRentalDetail", b =>
                {
                    b.Property<string>("RentalDetailId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("maCTT");

                    b.Property<string>("ServiceId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("maDV");

                    b.Property<DateTime>("UsageDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngaySuDung");

                    b.Property<int>("Price")
                        .HasColumnType("int")
                        .HasColumnName("giaDV");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("SoLuong");

                    b.HasKey("RentalDetailId", "ServiceId", "UsageDate");

                    b.HasIndex("ServiceId");

                    b.ToTable("CHITIETTHUEDICHVU");
                });

            modelBuilder.Entity("QuanLyKhachSan.Models.Account", b =>
                {
                    b.HasOne("QuanLyKhachSan.Models.Employee", "Employee")
                        .WithMany("Accounts")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyKhachSan.Models.Role", "Role")
                        .WithMany("Accounts")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("QuanLyKhachSan.Models.Invoice", b =>
                {
                    b.HasOne("QuanLyKhachSan.Models.RentalDetail", "RentalDetail")
                        .WithMany("Invoices")
                        .HasForeignKey("RentalDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RentalDetail");
                });

            modelBuilder.Entity("QuanLyKhachSan.Models.RentalDetail", b =>
                {
                    b.HasOne("QuanLyKhachSan.Models.Customer", "Customer")
                        .WithMany("RentalDetails")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyKhachSan.Models.Employee", "Employee")
                        .WithMany("RentalDetails")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("QuanLyKhachSan.Models.RoleFunction", b =>
                {
                    b.HasOne("QuanLyKhachSan.Models.Function", "Function")
                        .WithMany("RoleFunctions")
                        .HasForeignKey("FunctionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyKhachSan.Models.Role", "Role")
                        .WithMany("RoleFunctions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Function");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("QuanLyKhachSan.Models.RoomAmenity", b =>
                {
                    b.HasOne("QuanLyKhachSan.Models.Amenity", "Amenity")
                        .WithMany("RoomAmenities")
                        .HasForeignKey("AmenityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyKhachSan.Models.Room", "Room")
                        .WithMany("RoomAmenities")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Amenity");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("QuanLyKhachSan.Models.RoomRentalDetail", b =>
                {
                    b.HasOne("QuanLyKhachSan.Models.RentalDetail", "RentalDetail")
                        .WithMany("RoomRentalDetails")
                        .HasForeignKey("RentalDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyKhachSan.Models.Room", "Room")
                        .WithMany("RoomRentalDetails")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RentalDetail");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("QuanLyKhachSan.Models.ServiceRentalDetail", b =>
                {
                    b.HasOne("QuanLyKhachSan.Models.RentalDetail", "RentalDetail")
                        .WithMany("ServiceRentalDetails")
                        .HasForeignKey("RentalDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyKhachSan.Models.Service", "Service")
                        .WithMany("ServiceRentalDetails")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RentalDetail");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("QuanLyKhachSan.Models.Amenity", b =>
                {
                    b.Navigation("RoomAmenities");
                });

            modelBuilder.Entity("QuanLyKhachSan.Models.Customer", b =>
                {
                    b.Navigation("RentalDetails");
                });

            modelBuilder.Entity("QuanLyKhachSan.Models.Employee", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("RentalDetails");
                });

            modelBuilder.Entity("QuanLyKhachSan.Models.Function", b =>
                {
                    b.Navigation("RoleFunctions");
                });

            modelBuilder.Entity("QuanLyKhachSan.Models.RentalDetail", b =>
                {
                    b.Navigation("Invoices");

                    b.Navigation("RoomRentalDetails");

                    b.Navigation("ServiceRentalDetails");
                });

            modelBuilder.Entity("QuanLyKhachSan.Models.Role", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("RoleFunctions");
                });

            modelBuilder.Entity("QuanLyKhachSan.Models.Room", b =>
                {
                    b.Navigation("RoomAmenities");

                    b.Navigation("RoomRentalDetails");
                });

            modelBuilder.Entity("QuanLyKhachSan.Models.Service", b =>
                {
                    b.Navigation("ServiceRentalDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
